// JSON-LD markup generated by Google Structured Data Markup Helper
{
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "hacer sushi en casa",
    "image" : "https://sushifounder.com/img/sushiSoloTT.png",
    "description" : "Imagina preparar el mejor Sushi Roll, guiado por chef &#39;Gonzalo Vidal&#39; para que puedas compartilo con tu familia y amigos o para tu nuevo negocio",
    "brand" : {
      "@type" : "Brand",
      "logo" : "https://sushifounder.com/img/logo.svg"
    },
    "offers" : {
      "@type" : "Offer",
      "price" : "25.00"
    },
    "aggregateRating" : {
      "@type" : "AggregateRating",
      "ratingValue" : "4.8",
      "ratingCount" : "854"
    }
  }